### PR TITLE
Cython 3.0.10

### PR DESCRIPTION
**Pull request by lorentzenchr**
Similar to #7.
Build a wheel for Cython 3.0.10.

### CODE REVIEW

**Comment by lesteve** [comment]
@colesbury this would be nice if this PR could be merged since in scikit-learn our minimum dependency version is now 3.0.10 :pray:.

I completely understand if you have higher priorities. It is not super urgent on our side, we can certainly live with a nogil red CI for some time :wink:.

**Comment by colesbury** [comment]
Thanks for the reminder.

Wheel build: https://github.com/colesbury/nogil-wheels/actions/runs/8601724747

**Comment by lesteve** [comment]
Great, thanks a lot!

**Comment by lorentzenchr** [comment]
Thanks for merging.

**Pull request merged**
