### PR TITLE
Generate wheel for Cython 3.0.8

### PR DESCRIPTION
**Pull request by lesteve**
In scikit-learn we are testing nogil and we recently updated our minimum supported Cython version to 3.0.8 in https://github.com/scikit-learn/scikit-learn/pull/28284.

Let's be optimist and update this action to see whether that works :crossed_fingers:!

### CODE REVIEW

**Comment by lesteve** [comment]
@colesbury so this action is trigger manually (workflow_dispatch), I am not sure whether there is a way to test it in this PR ...

More generally I am wondering if other people have showed interest for Cython 3 in `nogil`. There may be some known issues that I am not aware of.

**Comment by lesteve** [comment]
@colesbury I have a modified version of Cython 3.0.8 that compiles. This modified Cython version can compile scikit-learn and the scikit-learn pass inside nogil-3.9.

The diff compared to Cython 3.0.8 is quite small, since I guess some work has been upstreamed into Cython:
https://github.com/cython/cython/compare/3.0.x...lesteve:cython:3.0.8-nogil?expand=1
- I cherry-picked two of your commits that still made sense on your 0.29.29-nogil tag and they moved some of the code to the right `elif` clause.
- 'CYTHON_METH_FASTCALL` needs to be disabled for Cython to compile
- I was not sure about `CYTHON_PEP489_MULTI_PHASE_INIT` so I kept the code as in your Cython fork

I am not sure what still needs to be done to turn it into a Cython 3 wheel in https://d1yxz45j0ypngg.cloudfront.net/cython/.

Of course, I completely understand if you have plenty of higher priority things to do!

If there is anything that I can help with, let me know!

**Comment by colesbury** [comment]
Thanks @lesteve. I added the `CYTHON_METH_FASTCALL` change to https://github.com/colesbury/cython/tree/3.0.8-nogil and a 3.0.x build file https://github.com/colesbury/nogil-wheels/blob/main/.github/workflows/cython-3.0.yml.

I starteed the wheel builds, but it looks like it will take the GitHub runners a little while to pick them up.

**Comment by colesbury** [comment]
Ah, thanks for the pointer!

**Comment by colesbury** [comment]
Ok, the Cython 3.0.8 wheel is uploaded. Please let me know if it works okay.

**Comment by lesteve** [comment]
Great, thanks!

Seems like the scikit-learn nogil build is happy in https://github.com/scikit-learn/scikit-learn/pull/28338 so I am happy too, let's close this one!

**Pull request closed without merging**
